# Base container that is used for both building and running the app
FROM quay.io/centos/centos:stream8 as base

RUN \
  dnf install -y redhat-rpm-config git-core \
    gcc-c++ make bzip2 gettext tar \
    libxml2-devel libcurl-devel ruby-devel \
    postgresql-devel && \
  dnf clean all

# SoF Custom
# https://thelinuxcluster.com/2023/06/30/compiling-glibc-2-29-at-centos-7/
RUN \
  dnf install -y wget bison python3.11; \
  which glibc; \
  wget -4c https://ftp.gnu.org/gnu/glibc/glibc-2.29.tar.gz; \
  tar -zxvf glibc-2.29.tar.gz; \
  cd glibc-2.29; \
  mkdir build_dir; \
  cd build_dir; \
  # ../configure --prefix=/opt/glibc; \
  ../configure --prefix=/usr/local/glibc-2.29; \
  make -j8; \
  make install; \
  dnf clean all

# EoF Custom

