
---
:enabled: true

# Log file for the forwarding script.
:openscap_send_log_file: /var/log/openscap-send.log

# Directory where OpenSCAP audits are stored
# before they are forwarded to Foreman
:spooldir: ~/.foreman-openscap/spool

# Directory where OpenSCAP content XML are stored
# So we will not request the XML from Foreman each time
:contentdir: ~/.foreman-openscap/content
# Directory where OpenSCAP report XML are stored
# So Foreman can request arf xml reports
:reportsdir: ~/.foreman-openscap/reports
