
FROM ruby:2.7-alpine3.16 as base


ARG HOME=/home/foreman


RUN mkdir -p ${HOME}

WORKDIR ${HOME}


RUN gem install rake bundler:2.4.22;


##########################################################################
#
#    Builder
#
##########################################################################
FROM base as builder


RUN apk add \
    alpine-sdk \
    libffi-dev \
    ruby-dev \
    ruby-rake \
    git; \
  git clone --depth=1 --branch 3.9.1 https://github.com/theforeman/smart-proxy.git /tmp/app; \
  rm -rf /tmp/app/.git; \
  cp -r /tmp/app/* ${HOME}/; \
  rm \
    bundler.d/libvirt.rb \
    bundler.d/krb5.rb \
    bundler.d/realm_freeipa.rb \
    bundler.d/windows.rb \
    bundler.d/bmc.rb \
    bundler.d/journald.rb;


COPY foreman_openscap_proxy.rb ${HOME}/bundler.d/

COPY smart_proxy_settings.yml ${HOME}/config/settings.yml

COPY openscap_settings.yml ${HOME}/config/settings.d/openscap.yml


ENV BUNDLER_SKIPPED_GROUPS="test development openid libvirt journald facter console"


RUN bundle config set --local without "${BUNDLER_SKIPPED_GROUPS}"; \
  bundle config set --local clean true; \
  bundle config set --local path vendor; \
  bundle config set --local jobs 5; \
  bundle config set --local retry 3


RUN bundle install; \
  bundle binstubs --all; \
  rm -rf vendor/ruby/*/cache/*.gem; \
  find vendor/ruby/*/gems -name "*.c" -delete; \
  find vendor/ruby/*/gems -name "*.o" -delete

# RUN bundle exec rake assets:clean assets:precompile;


RUN rm -rf vendor/ruby/*/cache vendor/ruby/*/gems/*/node_modules bundler.d/nulldb.rb db/schema.rb; \
  bundle config without "${BUNDLER_SKIPPED_GROUPS} assets"; \
  bundle install



##########################################################################
#
#    APP
#
##########################################################################
FROM base

ENV RAILS_ENV=production

ENV RAILS_SERVE_STATIC_FILES=true

ENV RAILS_LOG_TO_STDOUT=true


COPY --from=builder /tmp/app/. ${HOME}/

COPY --from=builder ${HOME}/bundle/config ${HOME}/bundle/config

COPY --from=builder ${HOME}/Gemfile.lock ${HOME}/Gemfile.lock

COPY --from=builder ${HOME}/vendor/ruby ${HOME}/vendor/ruby

COPY --from=builder ${HOME}/public ${HOME}/public


CMD bundle exec bin/smart-proxy



# cd smart_proxy_openscap

# bundle install

# gem build



# git clone --depth=1 --branch 3.9.1 https://github.com/theforeman/smart-proxy.git

# rm bundler.d/libvirt.rb
# rm bundler.d/krb5.rb
# rm bundler.d/realm_freeipa.rb
# rm bundler.d/windows.rb
# rm bundler.d/bmc.rb
# rm bundler.d/journald.rb

# bundle install --with development

# # to run
# bundle exec ruby bin/smart-proxy





# dockerfile

# copy --from=build smart_proxy_openscap-0.9.2.gem


# cat <<'EOF' > bundler.d/openscap.rb

# gem 'smart_proxy_openscap', :git => "https://github.com/theforeman/smart_proxy_openscap.git", :branch => 'v0.9.2'

# EOF