
ARG USER_GROUP_ID=65000

ARG USER_NAME=foreman

ARG SMART_PROXY_TAG=3.9.1


##########################################################################
#
#    Base
#
##########################################################################
# FROM ruby:2.7-alpine3.16 as foreman-base
FROM ruby:3.0.0-alpine as foreman-base

ARG USER_NAME $USER_NAME

ARG HOME /home/$USER_NAME

ARG USER_GROUP_ID $USER_GROUP_ID

ARG SMART_PROXY_TAG $SMART_PROXY_TAG

ENV HOME /home/$USER_NAME

ENV USER_GROUP_ID $USER_GROUP_ID

ENV USER_NAME $USER_NAME

ENV SMART_PROXY_VERSION $SMART_PROXY_TAG

ENV BUNDLE_APP_CONFIG='/home/foreman/.bundle'


RUN export; \
  addgroup -g ${USER_GROUP_ID} -S foreman; \
  adduser -S -h ${HOME} -u ${USER_GROUP_ID} -G foreman foreman; \
  chown 0:${USER_GROUP_ID} /var/log; \
  chmod 770 /var/log; \
  apk update --no-cache; \
  apk add --no-cache \
    nmap;


WORKDIR $HOME


##########################################################################
#
#    Builder
#
##########################################################################
FROM foreman-base as foreman-builder



ARG HOME /home/$USER_NAME

ARG USER_GROUP_ID $USER_GROUP_ID

ARG USER_NAME $USER_NAME


RUN apk add \
    alpine-sdk \
    libffi-dev \
    ruby-dev \
    ruby-rake \
    git;


RUN export; echo "${SMART_PROXY_VERSION}"; git clone --depth=1 --branch ${SMART_PROXY_VERSION} https://github.com/theforeman/smart-proxy.git /tmp/app; \
  rm \
    /tmp/app/bundler.d/libvirt.rb \
    /tmp/app/bundler.d/krb5.rb \
    /tmp/app/bundler.d/realm_freeipa.rb \
    /tmp/app/bundler.d/windows.rb \
    /tmp/app/bundler.d/bmc.rb \
    /tmp/app/bundler.d/journald.rb; \
  rm -rf /tmp/app/.git;


COPY --chown=${USER_GROUP_ID}:${USER_GROUP_ID} foreman_openscap_proxy.rb /tmp/app/bundler.d/

COPY --chown=${USER_GROUP_ID}:${USER_GROUP_ID} smart_proxy_settings.yml /tmp/app/config/settings.yml

COPY --chown=${USER_GROUP_ID}:${USER_GROUP_ID} openscap_settings.yml /tmp/app/config/settings.d/openscap.yml


RUN cp -r /tmp/app/* ${HOME}/; \
  chown -R ${USER_GROUP_ID}:${USER_GROUP_ID} ${HOME}/.; \
  chmod 770 -R ${HOME}/.;


ENV BUNDLER_SKIPPED_GROUPS="test development"


RUN bundle config set --local without "${BUNDLER_SKIPPED_GROUPS}";
#   bundle config set --local clean true; \
#   bundle config set --local path vendor; \
#   bundle config set --local jobs 5; \
#   bundle config set --local retry 3;

ENV BUNDLE_APP_CONFIG="/usr/local/bundle"

RUN bundle install;

RUN ls -la /usr/local/bundle

RUN bundle binstubs --all; 
  # rm -rf vendor/ruby/*/cache/*.gem; \
  # find vendor/ruby/*/gems -name "*.c" -delete; \
  # find vendor/ruby/*/gems -name "*.o" -delete

RUN gem install facter

# RUN rm -rf vendor/ruby/*/cache vendor/ruby/*/gems/*/node_modules bundler.d/nulldb.rb db/schema.rb; \
#   bundle install

RUN ls -la;


##########################################################################
#
#    APP
#
##########################################################################
FROM foreman-base as application

ENV BUNDLE_APP_CONFIG="/usr/local/bundle"

ARG USER_GROUP_ID $USER_GROUP_ID


USER $USER_GROUP_ID


COPY --from=foreman-builder --chown=${USER_GROUP_ID}:${USER_GROUP_ID} /tmp/app/. ${HOME}/

COPY --from=foreman-builder --chown=${USER_GROUP_ID}:${USER_GROUP_ID} ${HOME}/.bundle/config ${HOME}/.bundle/config

COPY --from=foreman-builder --chown=${USER_GROUP_ID}:${USER_GROUP_ID} ${HOME}/config ${HOME}/config

COPY --from=foreman-builder --chown=${USER_GROUP_ID}:${USER_GROUP_ID} ${HOME}/Gemfile.lock ${HOME}/Gemfile.lock

# COPY --from=foreman-builder --chown=${USER_GROUP_ID}:${USER_GROUP_ID} ${HOME}/vendor/ruby ${HOME}/vendor/ruby

COPY --from=foreman-builder --chown=${USER_GROUP_ID}:${USER_GROUP_ID} /usr/local/bundle /usr/local/bundle
USER 0
RUN apk add libc6-compat
USER $USER_GROUP_ID
CMD bundle exec bin/smart-proxy
