
FROM ruby:2.7-alpine3.16 as base

RUN export

ARG HOME=/home/foreman

RUN mkdir -p ${HOME}

WORKDIR ${HOME}

RUN bundle config set --local without "${BUNDLER_SKIPPED_GROUPS}"; \
  bundle config set --local clean true; \
  bundle config set --local path vendor; \
  bundle config set --local jobs 5; \
  bundle config set --local retry 3; \
  ls -la ${HOME};



ENV BUNDLE_APP_CONFIG='/home/foreman/.bundler'
ENV GEM_HOME "${HOME}/vendor/ruby/2.7.0"


# ENV GEM_HOME "${HOME}/vendor/ruby/2.7.0"
# ENV BUNDLE_APP_CONFIG=''

RUN gem install rake bundler:2.4.22;


##########################################################################
#
#    Builder
#
##########################################################################
FROM base as builder

ARG HOME=/home/foreman

# ENV GEM_HOME "${HOME}/vendor/ruby/2.7.0"
# ENV BUNDLE_APP_CONFIG=''


RUN apk add \
    alpine-sdk \
    libffi-dev \
    ruby-dev \
    ruby-rake \
    git; \
  git clone --depth=1 --branch 3.9.1 https://github.com/theforeman/smart-proxy.git /tmp/app; \
  rm \
    /tmp/app/bundler.d/libvirt.rb \
    /tmp/app/bundler.d/krb5.rb \
    /tmp/app/bundler.d/realm_freeipa.rb \
    /tmp/app/bundler.d/windows.rb \
    /tmp/app/bundler.d/bmc.rb \
    /tmp/app/bundler.d/journald.rb; \
  rm -rf /tmp/app/.git; \
  cp -r /tmp/app/* ${HOME}/; \
  cd ${HOME}; 



COPY foreman_openscap_proxy.rb ${HOME}/bundler.d/

COPY smart_proxy_settings.yml ${HOME}/config/settings.yml

COPY openscap_settings.yml ${HOME}/config/settings.d/openscap.yml


ENV BUNDLER_SKIPPED_GROUPS="test development openid libvirt journald facter console"

# ENV GEM_HOME=
# ENV BUNDLE_APP_CONFIG=
WORKDIR ${HOME}

# RUN export GEM_HOME=; export BUNDLE_APP_CONFIG=
# RUN ls -la; rm -rf .bundle; mkdir -p .bundle; \
#   echo "---" > .bundle/config; \
#   echo '"BUNDLE_PATH: "vendor"' > .bundle/config; \
#   ls -la; ls -la .bundle/ 

RUN export

RUN echo $PWD

RUN ls -la; cat .bundle/config

# RUN bundle config list

# RUN bundle --path=vendor; ls -la; ls -la .bundle/

# RUN bundle config set --local without "${BUNDLER_SKIPPED_GROUPS}"; \
#   bundle config set --local clean true; \
#   bundle config set --local path vendor; \
#   bundle config set --local jobs 5; \
#   bundle config set --local retry 3; \
#   ls -la;

# ENV BUNDLE_APP_CONFIG='${HOME}/vendor/bundle'

# RUN gem install rkerberos; \
RUN cd ${HOME}; \
  bundle install;

RUN bundle binstubs --all; \
  rm -rf vendor/ruby/*/cache/*.gem; \
  find vendor/ruby/*/gems -name "*.c" -delete; \
  find vendor/ruby/*/gems -name "*.o" -delete

# RUN bundle exec rake assets:clean assets:precompile;


RUN cd ${HOME}; rm -rf vendor/ruby/*/cache vendor/ruby/*/gems/*/node_modules bundler.d/nulldb.rb db/schema.rb; \
  bundle config without "${BUNDLER_SKIPPED_GROUPS} assets"; \
  bundle install


RUN echo "1"; ls -la ${HOME}; ls -laR ${HOME}/.bundle


##########################################################################
#
#    APP
#
##########################################################################
FROM base

# ENV GEM_HOME ""
# ENV BUNDLE_APP_CONFIG=''

ARG HOME=/home/foreman

# ENV GEM_HOME "${HOME}/vendor/ruby/2.7.0"

ENV RAILS_ENV=production

ENV RAILS_SERVE_STATIC_FILES=true

ENV RAILS_LOG_TO_STDOUT=true

WORKDIR ${HOME}

COPY --from=builder /tmp/app/. ${HOME}/

# RUN ls -l ${HOME}
COPY --from=builder ${HOME}/.bundle/config ${HOME}/.bundle/config

COPY --from=builder ${HOME}/config ${HOME}/config

COPY --from=builder ${HOME}/Gemfile.lock ${HOME}/Gemfile.lock

COPY --from=builder ${HOME}/vendor/ruby ${HOME}/vendor/ruby

# COPY --from=builder ${HOME}/public ${HOME}/public

# RUN gem install rkerberos;

CMD bundle exec bin/smart-proxy



# cd smart_proxy_openscap

# bundle install

# gem build



# git clone --depth=1 --branch 3.9.1 https://github.com/theforeman/smart-proxy.git

# rm bundler.d/libvirt.rb
# rm bundler.d/krb5.rb
# rm bundler.d/realm_freeipa.rb
# rm bundler.d/windows.rb
# rm bundler.d/bmc.rb
# rm bundler.d/journald.rb

# bundle install --with development

# # to run
# bundle exec ruby bin/smart-proxy





# dockerfile

# copy --from=build smart_proxy_openscap-0.9.2.gem


# cat <<'EOF' > bundler.d/openscap.rb

# gem 'smart_proxy_openscap', :git => "https://github.com/theforeman/smart_proxy_openscap.git", :branch => 'v0.9.2'

# EOF