name: Build multi-platform Docker image
 
on: 
  workflow_dispatch: {}
 
jobs:
  build-with-docker:
    name: Build multi-platform Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      # - uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     platforms: linux/arm64
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      - name: Log into registry ghcr.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     platforms: linux/arm64,linux/amd64
      #     push: true
      #     tags: ghcr.io/${{ github.repository_owner }}/glibc229:${{ github.sha }}
      #     file: Dockerfile-glibc
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/foreman-amd64:3.9.1
          file: Dockerfile-amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max