name: Build multi-platform Docker image
 
on:
  push: {}

# on:
#   workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-with-docker:
    name: Build multi-platform Docker image
    runs-on: ubuntu-latest



    permissions:
      contents: read
      packages: write


    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      # - uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     platforms: linux/arm64
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     platforms: linux/arm64,linux/amd64
      #     push: true
      #     tags: ghcr.io/${{ github.repository_owner }}/glibc229:${{ github.sha }}
      #     file: Dockerfile-glibc
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


      - uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:foreman-3.9.1-katello
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max